# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aec86f6db77b38b733545dddbacf97295ba206b0b922540b66fa78f06400318938abb431f22aaa100e92d4cc2579d38463665253ae05c65b9f2acf836510edc4

test:
  secret_key_base: 0900090d9135ddadb731a87988a3eb11cab7efb28e33c2eff35c02c7898f172e7fe59a6cd9e6a58b04e8e9301fc66318ce3502635d7b764b4716ed75f185b2de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
